# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 04:28
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managerawdata', '0007_auto_20160905_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='opage',
            name='bars',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
    ]