# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 05:53
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('segmentation', '0002_auto_20160906_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=128)),
                ('reply', models.CharField(blank=True, max_length=128)),
                ('comment_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('replay_at', models.DateTimeField(blank=True)),
                ('state', models.CharField(choices=[(b'PE', b'\xe5\xbe\x85\xe5\xa4\x84\xe7\x90\x86'), (b'DN', b'\xe5\xb7\xb2\xe5\xa4\x84\xe7\x90\x86'), (b'RJ', b'\xe5\xb7\xb2\xe6\x8b\x92\xe7\xbb\x9d'), (b'AP', b'\xe5\xb7\xb2\xe6\x8e\xa5\xe5\x8f\x97')], default=b'PE', max_length=2)),
                ('admin', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL)),
                ('collator', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='page',
            old_name='is_correct',
            new_name='state',
        ),
        migrations.AddField(
            model_name='pagecomment',
            name='page',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='segmentation.Page'),
        ),
    ]
