# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 07:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('segmentation', '0003_auto_20160919_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecomment',
            name='page',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='page_comment', to='segmentation.Page'),
        ),
    ]
