# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layoutseg', '0002_region_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='bottom',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='region',
            name='left',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='region',
            name='line_no',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='region',
            name='region_no',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='region',
            name='right',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='region',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='top',
            field=models.SmallIntegerField(default=0),
        ),
    ]
