# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 13:25
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_auto_20160824_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripitaka',
            name='default_bars',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[(100, 60, 1250, 1020), (80, 1050, 1250, 2000)]),
        ),
    ]
