# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('catalogue', '0004_tripitaka_default_bars'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripitaka',
            name='completed_count',
            field=models.SmallIntegerField(default=0, verbose_name='Tripitaka|completed_count'),
        ),
        migrations.AddField(
            model_name='volume',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.UserProfile'),
        ),
    ]
