# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 01:29
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_auto_20160918_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripitaka',
            name='completed_volume_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=32), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='volume',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volumes', to='account.UserProfile'),
        ),
    ]
