# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_auto_20160919_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='completed_count',
            field=models.SmallIntegerField(default=0, verbose_name='Volume|completed_count'),
        ),
        migrations.AddField(
            model_name='volume',
            name='state',
            field=models.SmallIntegerField(default=0, verbose_name='Volume|state'),
        ),
        migrations.AddField(
            model_name='volume',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
