export const COLLECTION_IS_LOADING = "PAGE_COMMENTS_IS_LOADING";
export const RECEIVED_COLLECTION = "RECEIVED_PAGE_COMMENTS";
export const RECEIVED_MODEL = "RECEIVED_PAGE_COMMENT";
export const REMOVED_MODEL = "REMOVED_MODEL";
export const UPDATE_COLLECTION_QUERY = "UPDATE_PAGE_COMMENTS_QUERY";

export default {
    COLLECTION_IS_LOADING,
    RECEIVED_COLLECTION,
    RECEIVED_MODEL,
    REMOVED_MODEL,
    UPDATE_COLLECTION_QUERY
};
